services:
  localstack:
    image: localstack/localstack:3.0
    container_name: football-localstack
    environment:
      - SERVICES=s3,lambda,cloudformation,apigateway,iam,ssm,cloudformation
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - LAMBDA_DOCKER_NETWORK=host
      - LAMBDA_REMOTE_DOCKER=false
      - LOCALSTACK_HOST=localhost
      - HOSTNAME_EXTERNAL=localhost
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
    ports:
      - "4566:4566"
    volumes:
      - ./lambda:/var/task
      - /var/run/docker.sock:/var/run/docker.sock
