version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: football-localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=dynamodb,events,apigateway,lambda,cloudformation,iam
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - LAMBDA_DOCKER_NETWORK=host
      - LAMBDA_REMOTE_DOCKER=false
      - MAIN_CONTAINER_NAME=football-localstack
    volumes:
      - ./:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
