version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=dynamodb,events,apigateway,lambda,cloudformation,iam,ssm,sqs,cloudwatch
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - LAMBDA_DOCKER_NETWORK=host
      - MAIN_CONTAINER_NAME=football-localstack
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_PREBUILD_IMAGES=1
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - ./lambda:/var/task
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      localnet:
        aliases:
          - s3.localhost.localstack.cloud

networks:
  localnet:
    driver: bridge
